server:
  port: 8080
  address: 0.0.0.0

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: sistema-nutricao

  datasource:
    url: {DATASOURCE_URL}
    username: {DATASOURCE_USERNAME}
    password: {DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dmjesus89@gmail.com}
    password: ${MAIL_PASSWORD:vuke fiiv micf ukxu}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

# Custom Application Properties
app:
  frontend:
    url: {FRONTEND_URL}

  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 604800000 # 7 days
    refresh-expiration: 604800000 # 7 days

  email:
    from: ${EMAIL_FROM:dmjesus89@gmail.com}
    confirmation:
      expiration: 86400000 # 24 hours
    reset-password:
      expiration: 3600000 # 1 hour

  rate-limit:
    login:
      attempts: 5
      window: 30 # 0.5 minutes in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

#logging:
#  level:
#    com.nutrition: INFO
#    org.springframework.security: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/sistema-nutricao.log