server:
  port: 8080
  address: 0.0.0.0

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: sistema-nutricao

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080


app:
  frontend:
    url: ${FRONTEND_URL}

  jwt:
    secret: ${JWT_SECRET}
    expiration: 604800000 # 7 days
    refresh-expiration: 604800000 # 7 days

  email:
    confirmation:
      expiration: 86400000 # 24 hours
    reset-password:
      expiration: 3600000 # 1 hour

  rate-limit:
    login:
      attempts: 5
      window: 30 # 0.5 minutes in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized


      